feat: policy-based deployment
edgexfoundry-holding/orra pull request #18
Opened 2022-10-03 16:47 UTC by ajcasagrande

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

Pattern only deployment

## Issue Number:

## What is the new behavior?
Support for policy-based deployments, which allows user to register a node, and then later assign it a workload through node properties.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

MQTT-over-websocket port has been changed from 9001 to 59001 to avoid port conflicts.

2022-10-04 18:58 UTC, presatish requested changes
Mostly looks goods just some files missing license headers.

2022-10-04 18:58 UTC, presatish commented on demos/OH-EXF-Kamakura/src/app-camera-management/service.policy.json
> +{
Need to add the license header as I remember you adding for other json files before.

2022-10-04 18:58 UTC, presatish commented on demos/OH-EXF-Kamakura/src/asc-mqtt/service.policy.json
> +{
Missing license header.

2022-10-04 18:58 UTC, presatish commented on demos/OH-EXF-Kamakura/src/edgex-ui/service.policy.json
> +{
Missing license header

2022-10-04 18:58 UTC, presatish commented on demos/OH-EXF-Kamakura/horizon/node-policy.json
>  {
Missing license header.

2022-10-05 16:18 UTC, ajcasagrande commented on demos/OH-EXF-Kamakura/src/app-camera-management/service.policy.json
> +{
@presatish These files are not sent through the json pre-processor, so license header cannot be added. I also do not think it is that important for these files.

2022-10-05 17:17 UTC, presatish approved these changes

2022-10-20 18:59 UTC, ajcasagrande commented
@joewxboy

2022-10-20 19:14 UTC, joewxboy approved these changes

2022-10-20 19:14 UTC, merged